/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortUrlRouteImport } from './routes/$shortUrl'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageUrlRouteImport } from './routes/manage/$url'
import { Route as CheckUrlRouteImport } from './routes/check/$url'

const ShortUrlRoute = ShortUrlRouteImport.update({
  id: '/$shortUrl',
  path: '/$shortUrl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUrlRoute = ManageUrlRouteImport.update({
  id: '/manage/$url',
  path: '/manage/$url',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckUrlRoute = CheckUrlRouteImport.update({
  id: '/check/$url',
  path: '/check/$url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
  '/check/$url': typeof CheckUrlRoute
  '/manage/$url': typeof ManageUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
  '/check/$url': typeof CheckUrlRoute
  '/manage/$url': typeof ManageUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
  '/check/$url': typeof CheckUrlRoute
  '/manage/$url': typeof ManageUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortUrl' | '/check/$url' | '/manage/$url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortUrl' | '/check/$url' | '/manage/$url'
  id: '__root__' | '/' | '/$shortUrl' | '/check/$url' | '/manage/$url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortUrlRoute: typeof ShortUrlRoute
  CheckUrlRoute: typeof CheckUrlRoute
  ManageUrlRoute: typeof ManageUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shortUrl': {
      id: '/$shortUrl'
      path: '/$shortUrl'
      fullPath: '/$shortUrl'
      preLoaderRoute: typeof ShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$url': {
      id: '/manage/$url'
      path: '/manage/$url'
      fullPath: '/manage/$url'
      preLoaderRoute: typeof ManageUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/$url': {
      id: '/check/$url'
      path: '/check/$url'
      fullPath: '/check/$url'
      preLoaderRoute: typeof CheckUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortUrlRoute: ShortUrlRoute,
  CheckUrlRoute: CheckUrlRoute,
  ManageUrlRoute: ManageUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
